import { useState } from 'react';
import type { TrailerResponse } from '../types';

interface Props {
  result: TrailerResponse;
  onNew: () => void;
}

export default function ActionBar({ result, onNew }: Props) {
  const [liked,   setLiked]   = useState(false);
  const [copied,  setCopied]  = useState(false);
  const [shared,  setShared]  = useState(false);

  async function handleShare() {
    const shareText = `🎬 ${result.title}\n"${result.tagline}"\n\nGenerated by Bollywood-ify My Day`;
    if (navigator.share) {
      try {
        await navigator.share({
          title: result.title,
          text: shareText,
          url: window.location.href,
        });
        setShared(true);
        setTimeout(() => setShared(false), 2000);
      } catch {
        // user cancelled — no-op
      }
    } else {
      // Fallback: copy poster URL to clipboard
      await navigator.clipboard.writeText(`${shareText}\n\nPoster: ${result.posterUrl}`);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  }

  async function handleCopy() {
    const text = `🎬 ${result.title}\n"${result.tagline}"`;
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="action-bar" role="toolbar" aria-label="Trailer actions">
      {/* New / create */}
      <button
        className="action-bar__btn action-bar__btn--primary"
        onClick={onNew}
        title="Create a new day"
        aria-label="Create new"
      >
        <span className="action-bar__icon">✚</span>
        <span className="action-bar__label">New</span>
      </button>

      <div className="action-bar__divider" aria-hidden="true" />

      {/* Like */}
      <button
        className={`action-bar__btn${liked ? ' action-bar__btn--liked' : ''}`}
        onClick={() => setLiked(l => !l)}
        title={liked ? 'Liked!' : 'Like this trailer'}
        aria-label={liked ? 'Unlike' : 'Like'}
        aria-pressed={liked}
      >
        <span className="action-bar__icon">{liked ? '❤️' : '🤍'}</span>
      </button>

      {/* Share */}
      <button
        className="action-bar__btn"
        onClick={handleShare}
        title="Share trailer"
        aria-label="Share"
      >
        <span className="action-bar__icon">{shared ? '✓' : '↗'}</span>
      </button>

      {/* Copy title + tagline */}
      <button
        className="action-bar__btn"
        onClick={handleCopy}
        title="Copy title and tagline"
        aria-label="Copy"
      >
        <span className="action-bar__icon">{copied ? '✓' : '⎘'}</span>
      </button>

      {/* Download poster */}
      <button
        className="action-bar__btn"
        onClick={async () => {
          try {
            const res = await fetch(result.posterUrl);
            const blob = await res.blob();
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${result.title.replace(/\s+/g, '-')}-poster.jpg`;
            a.click();
            URL.revokeObjectURL(url);
          } catch {
            window.open(result.posterUrl, '_blank');
          }
        }}
        title="Download poster"
        aria-label="Download poster"
      >
        <span className="action-bar__icon">⬇</span>
      </button>
    </div>
  );
}
